### ISSUE TITLE
Duplicated SHA in checksumfile

### ISSUE THREAD

**Issue by pbertera** [kazuhisya/openshift-ansible-kvm#32]
Hi,

it seems that the openshift shasum file now contains a duplicated SHA:

from https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.0/sha256sum.txt

```
29ba7e12b16f143a3f036226568ce91b3f7c8bd6feab719a73b0bed1817e4444  rhcos-4.7.0-x86_64-live-initramfs.x86_64.img
7da6617f6bb7b29c0a8cba002642f2fa23d954874e0d3641e61dd59573563381  rhcos-4.7.0-x86_64-live-kernel-x86_64
[...]
29ba7e12b16f143a3f036226568ce91b3f7c8bd6feab719a73b0bed1817e4444  rhcos-live-initramfs.x86_64.img
7da6617f6bb7b29c0a8cba002642f2fa23d954874e0d3641e61dd59573563381  rhcos-live-kernel-x86_64
```
Unfortunately, due to https://github.com/ansible/ansible/issues/71420 this breaks the playbook.

I did not check with all the OCP versions, but on 4.6 and 4.7 using the short name ( Eg. `rhcos-live-kernel-x86_64` ) is a workaround.

**Comment by kazuhisya** [comment]
Hi @pbertera,

Thank you for reporting!
I already knew this problem and was making #27.
But I haven't been able to take care of this these days...

> I did not check with all the OCP versions, but on 4.6 and 4.7 using the short name ( Eg. rhcos-live-kernel-x86_64 ) is a workaround.

Your suggestion is very helpful. I think probably it will work.
I would like to try this later.

Thank you so much!

**Comment by pbertera** [comment]
It seems that started changing between 4.4.3 and 4.4.17:

https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.4/4.4.3/
https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.4/4.4.17/

**Comment by kazuhisya** [comment]
Hi @pbertera,

Thank you for the information.
I tweaked code that just a little bit. and tried few patterns.
Then, It looks good.(for now)

- Tested version:
    - 4.7.1
    - 4.6.1
    - 4.5.6
    - 4.4.17
    - 4.4.3

I'll test a little more and marge to the main branch.
